kind: pipeline
type: docker
name: Re-deploy Swarm Stack

# After you push the changes to the GitHub repository, the preconfigured automated build process is started in the Docker Hub. When the container are successfully built from the chosen Dockerfiles, the pipeline can then proceed with the next deployment step. In that step the new versions of the containers are being pulled from the Docker Registry and re-deployed in the swarm stack.
# Any pipeline step can be triggered on the so-called 'custom' event coming from the docker hub using it's outgoing webhook (or from any other CI tool or container registry, such as GitHub registry or similar: https://github.com/features/packages):
# http://IP_OR_DNS:PORT/api/repos/<github-user>/<github-repo>/builds?branch=<branch-name>&access_token=<32-characters-long-hash>
# The personal bearer auth token can be found in your Drone account: http://IP_OR_DNS:PORT/account
# There are more pipeline parameters and other details on this page: https://docs.drone.io/api/builds/build_create/
# Finally, set up that url in the docker hub webhook's tab in the repository that's being built last of all: https://hub.docker.com/repository/docker/<organization/repo-name>/webhooks

# Deployments can also be triggered using GitHub's actions and/or plugins:
# https://probot.github.io/docs/deployment/
# https://developer.github.com/webhooks/#events
# https://developer.github.com/v3/repos/deployments/

steps:
  # ssh into the machine and deploy the docker image (pseudo code).
  # http://plugins.drone.io/appleboy/drone-ssh/
  - name: deploy
    image: appleboy/drone-ssh
    when:
      event:
        - custom
        # - promote
        # - cron
        # - push
        # - pull_request
        # - tag
        # - rollback
      # branch:
      #   - dockerized
      # target:
      #   - production
      # https://docs.drone.io/pipeline/docker/syntax/conditions/#by-status
      # https://docs.drone.io/promote/
    environment:
      FILE_PATH:
        from_secret: file_path
      FILE_NAME:
        from_secret: file_name
      STACK_NAME:
        from_secret: stack_name
    # https://github.com/appleboy/drone-ssh/issues/130
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      # key:
      #   from_secret: ssh_key
      # passphrase: 1234
      port: 22
      envs: [FILE_PATH, FILE_NAME, STACK_NAME]
      script:
        - echo "The deployment has been started."
        - echo "Docker Compose file path is:"
        - echo $FILE_PATH/$FILE_NAME
        - echo "The name of the stack file:"
        - echo $STACK_NAME
        # - docker stop myprogram
        # - docker pull company/project:${DRONE_COMMIT}
        # - docker run -d company/project:${DRONE_COMMIT} myprogram
        - docker stack deploy -c $FILE_PATH/$FILE_NAME $STACK_NAME
  # https://discourse.drone.io/t/triggering-promotion-event/6634/7

  # Notify Telegram about the deployment status (about the github commit)
  - name: telgram_notify
    image: appleboy/drone-telegram
    when:
      status:
        - success
        - failure
    settings:
      # The secrets below can be entered from the Drone UI for this repo
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_chat_id
      format: markdown
      message: >
        {{#success build.status}}
        ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ```
        {{commit.message}}
        ```
        🌐 {{ build.link }}
        {{else}}
        ❌ Build #{{build.number}} of `{{repo.name}}` failed.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ```
        {{commit.message}}
        ```
        🌐 {{ build.link }}
        {{/success}}

# https://docs.drone.io/pipeline/triggers/#by-event
trigger:
  event:
    exclude: [push, tag]
    # [ pull_request, promote, rollback, custom ]
# ---
#   kind: secret
#   name: foo
#   data: EUgsPFbn0xyNdsxKtbB6nwR2w7RdG1pzo299qmI4zQ==
# https://gist.github.com/phildionne/790d90a390c7d345bba71c20f56c0026
