kind: pipeline
type: docker
name: deploy

# Any step can be triggered from the docker hub (or from any other CI tool / registry) using the outgoing webhook:
# http://IP_OR_DNS:PORT/api/repos/<github-user>/<github-repo>/builds?branch=<branch-name>&access_token=32-characters-long-hash
# The personal token can be found in here: http://IP_OR_DNS:PORT/account
# See for more parameters and other details: https://docs.drone.io/api/builds/build_create/
# Finally, add that url (webhook) in docker hub here: https://hub.docker.com/repository/docker/<organization/repo-name>/webhooks

# Deployments using GitHub's actions and plugins: https://probot.github.io/docs/deployment/

steps:
  # ssh into the machine and deploy the docker image (pseudo code).
  # http://plugins.drone.io/appleboy/drone-ssh/
  - name: deploy
    image: appleboy/drone-ssh
    when:
      branch:
        - dockerized
      event:
        - custom
        # - promote
        # - cron
        # - push
        # - pull_request
        # - tag
        # - rollback
      target:
        - production
      # https://docs.drone.io/pipeline/docker/syntax/conditions/#by-status
      # https://docs.drone.io/promote/
    # environment:
    #   USERNAME:
    #     from_secret: docker_username
    #   PASSWORD:
    #     from_secret: docker_password
    # https://docs.drone.io/secret/repository/
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      # key:
      #   from_secret: ssh_key
      # passphrase: 1234
      port: 22
      # envs:
      #   - date
      # script:
      #   - export BUILD_DATE=$DATE
      script:
        - echo "The deployment has been triggered."
        # - docker stop myprogram
        # - docker pull company/project:${DRONE_COMMIT}
        # - docker run -d company/project:${DRONE_COMMIT} myprogram
        - cd docker-swarm-stack/
        - docker stack deploy -c drone-prod-stack.example.yml stack-name
  # https://discourse.drone.io/t/triggering-promotion-event/6634/7

  # Notify Telegram about the deployment status (about the github commit)
  - name: telgram_notify
    image: appleboy/drone-telegram
    when:
      status:
        - success
        - failure
    settings:
      # The secrets below can be entered from the Drone UI for this repo
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_chat_id
      format: markdown
      message: >
        {{#success build.status}}
        ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ```
        {{commit.message}}
        ```
        🌐 {{ build.link }}
        {{else}}
        ❌ Build #{{build.number}} of `{{repo.name}}` failed.
        📝 Commit by {{commit.author}} on `{{commit.branch}}`:
        ```
        {{commit.message}}
        ```
        🌐 {{ build.link }}
        {{/success}}

# https://docs.drone.io/pipeline/triggers/#by-event
trigger:
  event:
    exclude:
      - push
    # [ pull_request, tag, promote, rollback, custom ]
# ---
#   kind: secret
#   name: foo
#   data: EUgsPFbn0xyNdsxKtbB6nwR2w7RdG1pzo299qmI4zQ==
# https://gist.github.com/phildionne/790d90a390c7d345bba71c20f56c0026
