version: '3.7'

services:
  frontend:
    image: fuzzysouls/tg-aggregator-frontend:latest
    container_name: frontend-service
    ports:
      - 80:3000
      # published=<PUBLISHED-PORT>,target=<CONTAINER-PORT>
      - published: 80
      - target: 3000
      - protocol: tcp
    networks:
      - microservices
      - traefik_proxy
    environment:
      # - 'ES_CONNECTION_URI=${ES_CONNECTION_URI}'
    deploy:
      labels:
        # network
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik_proxy'

        # routers
        - 'traefik.http.routers.frontend-router.rule=HostRegexp(`example.com`,`subdomain:[a-z]+}.example.com`)'
        # - 'traefik.http.routers.frontend-router.entrypoints=web'
        - 'traefik.http.routers.frontend-router.tls=true'
        - 'traefik.http.routers.frontend-router.entrypoints=web-secure'
        - 'traefik.http.routers.frontend-router.tls.certresolver=mycert'
        # - 'traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)'
        # - 'traefik.http.routers.http_catchall.entrypoints=web'
        # - 'traefik.http.routers.http_catchall.middlewares=https_redirect'

        # services
        - 'traefik.http.services.frontend-service.loadbalancer.server.port=80'
        - 'traefik.http.services.frontend-service.loadbalancer.server.scheme=https'
        # TODO: assign the service named 'frontend-service' in swarm
        # https://docs.traefik.io/routing/providers/docker/#service-definition
        # - 'traefik.port=3000'
        # middlewares
        # - 'traefik.http.middlewares.https_redirect.redirectscheme.scheme=https'
        # - 'traefik.http.middlewares.https_redirect.redirectscheme.permanent=true'
        # https://docs.traefik.io/migration/v1-to-v2/#http-to-https-redirection-is-now-configured-on-routers
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  # dynamic configuration: https://docs.traefik.io/reference/dynamic-configuration/docker/
  backend:
    image: fuzzysouls/tg-aggregator-backend:latest
    container_name: backend-service
    ports:
      - '8080:8080'
    networks:
      - microservices
      - traefik_proxy
    environment:
      # - 'BOT_TOKEN=${BOT_TOKEN}'
      # - 'CONNECTION_STRING=${CONNECTION_STRING}'
      # - 'APPLICATION_KEY=${APPLICATION_KEY}'
      # - 'APPLICATION_SECRET=${APPLICATION_SECRET}'
    deploy:
      labels:
        # network
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik_proxy'

        # routers
        - 'traefik.http.routers.backend-router.rule=Host(`mydomain.com`)'
        - 'traefik.http.routers.backend-router.entrypoints=backend'
        # no need for TLS on the backend, as it's in internal network anyway
        # - 'traefik.http.routers.backend-router.tls=true'
        # - "traefik.http.routers.backend-router.entrypoints=back-secure"
        # - 'traefik.http.routers.backend-router.tls.certresolver=mycert'

        # services
        - 'traefik.http.services.backend-service.loadbalancer.server.port=8080'
        - 'traefik.http.services.backend-service.loadbalancer.server.scheme=http'
        # TODO: use the the service name (e.g. 'backend-service') assigned in swarm
        # https://docs.traefik.io/routing/providers/docker/#service-definition
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: start-first
        monitor: 30s
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.33'
          memory: 128M

  # global routing server & dashboard configuration / reverse proxy
  # https://github.com/cbirkenbeul/docker-homelab/tree/master/traefik
  # TODO: docker network create traefik_proxy
  traefik:
    container_name: traefik-service
    restart: always
    image: traefik:v2.1.1
    command: --configFile=/etc/traefik/traefik.toml # read it from the volume
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
      - '8080:8080/tcp' # backend
      - '8088:8088/tcp' # drone entry-point
      - '9000:9000/tcp' # traefik dashboard
    networks:
      - traefik_proxy
      - microservices
      - drone
      # - drone_ci # no need to load balance that network
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: start-first
        monitor: 30s
      placement:
        constraints:
          - node.role == manager
      labels:
        # network
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik_proxy'

        # routers
        - 'traefik.http.routers.api.rule=Host(`traefik.example.com`) && PathPrefix(`/dashboard`)' # change to your domain
        - 'traefik.http.routers.api.entryPoints=dashboard'
        - 'traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)'
        - 'traefik.http.routers.api.service=api@internal'
        # - 'traefik.http.routers.api.middlewares=auth'

        # services
        - 'traefik.http.services.traefik-service.loadbalancer.server.port=9000'
        - 'traefik.http.services.traefik-service.loadbalancer.server.scheme=https'
        # - 'traefik.port=9000'
        # middlewares
        # - 'traefik.http.middlewares.auth.basicauth.users=<user>/<pass>'
        # configuration example: https://docs.traefik.io/migration/v1-to-v2/
        # https://docs.traefik.io/operations/dashboard/#secure-mode
        # TODO: paste <user>/<pass> in the above line by generating with:
        # sudo apt install apache2-utils -y
        # echo $(htpasswd -nbB <USER> "<PASS>") | sed -e s/\\$/\\$\\$/g
        # You can then access the dashboard at http://traefik.example.com:9000 or at http://<Traefik IP>:9000/dashboard/
        # or just do: curl -s 127.0.0.1:9000/api/rawdata | jq .
    depends_on:
      - backend
      - frontend
      # - drone-server
      # - drone-agent
      # - search
      # - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/volumes/traefik/log:/log
      - /etc/localtime:/etc/localtime
      - ${PWD}/config:/etc/traefik
      # - ./config/traefik.toml:/etc/traefik/traefik.toml
      # - ./config/acme/acme.json:/etc/traefik/acme/acme.json

# do not use the 'bridge' network on swarm if you need port communications between nodes
networks:
  microservices:
    driver: overlay
    external: false # TODO: will the frontend service still be reachable (crawling requests)?
    attachable: true
    # internal: true # to block access to the outside world
  traefik_proxy:
    driver: overlay
    external: true
    attachable: true
# ----------------------------------
# services:
#   search:
#     build: './search'
#     image: elasticsearch
#     ports:
#       - "9200:9200"
#     ports:
#       - '9243:9000'
#     depends_on:
#       - db
#     environment:
#       - ELASTICSEARCH_URI=

#   db:
#     image: mongo
#     ports:
#       - '27017:27017'
#     # volumes:
# ----------------------------------
# delegate load balancing to swarm by setting:
# - "traefik.docker.lbswarm=true"
# https://docs.traefik.io/v2.0/routing/providers/docker/#traefikdockerlbswarm
