version: '3.7'

services:
  frontend:
    image: fuzzysouls/tg-aggregator-frontend:latest
    ports:
      # - 80:3000 # old syntax
      # published=<PUBLISHED-PORT>,target=<CONTAINER-PORT>
      - published: 80
      - target: 3000
      - protocol: tcp
    networks:
      - microservices
      - traefik_proxy
    environment:
      # - 'ES_CONNECTION_URI=${ES_CONNECTION_URI}'
    deploy:
      labels:
        # network
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik_proxy'

        # routers
        - 'traefik.http.routers.frontend-router.rule=HostRegexp(`example.com`,`subdomain:[a-z]+}.example.com`)'
        # - 'traefik.http.routers.frontend-router.entrypoints=web'
        - 'traefik.http.routers.frontend-router.tls=true'
        - 'traefik.http.routers.frontend-router.tls.certresolver=godaddy-resolver'
        - 'traefik.http.routers.frontend-router.entrypoints=web-secure'
        # - 'traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)'
        # - 'traefik.http.routers.http_catchall.entrypoints=web'
        # - 'traefik.http.routers.http_catchall.middlewares=https_redirect'

        # services
        - 'traefik.http.services.frontend.loadbalancer.server.port=80'
        - 'traefik.http.services.frontend.loadbalancer.server.scheme=https'
        # TODO: assign the service named 'frontend-service' in swarm
        # https://docs.traefik.io/routing/providers/docker/#service-definition
        # - 'traefik.port=3000'
        # middlewares
        # - 'traefik.http.middlewares.https_redirect.redirectscheme.scheme=https'
        # - 'traefik.http.middlewares.https_redirect.redirectscheme.permanent=true'
        # https://docs.traefik.io/migration/v1-to-v2/#http-to-https-redirection-is-now-configured-on-routers
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  # dynamic configuration: https://docs.traefik.io/reference/dynamic-configuration/docker/
  backend:
    image: fuzzysouls/tg-aggregator-backend:latest
    ports:
      - '8080:8080'
    networks:
      - microservices
      - traefik_proxy
    environment:
      # - 'BOT_TOKEN=${BOT_TOKEN}'
      # - 'CONNECTION_STRING=${CONNECTION_STRING}'
      # - 'APPLICATION_KEY=${APPLICATION_KEY}'
      # - 'APPLICATION_SECRET=${APPLICATION_SECRET}'
    deploy:
      labels:
        # network
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik_proxy'

        # routers
        - 'traefik.http.routers.backend-router.rule=Host(`mydomain.com`)'
        - 'traefik.http.routers.backend-router.entrypoints=backend'
        # no need for TLS on the backend, as it's in internal network anyway
        # - 'traefik.http.routers.backend-router.tls=true'
        # - "traefik.http.routers.backend-router.entrypoints=back-secure"
        # - 'traefik.http.routers.backend-router.tls.certresolver=godaddy-resolver'

        # services
        - 'traefik.http.services.backend.loadbalancer.server.port=8080'
        - 'traefik.http.services.backend.loadbalancer.server.scheme=http'
        # TODO: use the the service name (e.g. 'backend-service') assigned in swarm
        # https://docs.traefik.io/routing/providers/docker/#service-definition
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: start-first
        monitor: 30s
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.33'
          memory: 128M
# do not use the 'bridge' network on swarm in production if you need port communications between nodes: https://docs.docker.com/network/overlay/
# networks:
#   microservices:
#     driver: overlay
#     external: false # TODO: will the frontend service still be reachable (crawling requests)?
#     attachable: true
# internal: true # to block access to the outside world
# ----------------------------------
# services:
#   search:
#     build: './search'
#     image: elasticsearch
#     ports:
#       - "9200:9200"
#     ports:
#       - '9243:9100'
#     depends_on:
#       - db
#     environment:
#       - ELASTICSEARCH_URI=

#   db:
#     image: mongo
#     ports:
#       - '27017:27017'
#     # volumes:
# ----------------------------------
# delegate load balancing to swarm by setting:
# - "traefik.docker.lbswarm=true"
# https://docs.traefik.io/v2.0/routing/providers/docker/#traefikdockerlbswarm
